# Sleep
exec-once = ~/.config/hypr/scripts/sleep.sh
# Waybar
# exec-once = ~/.config/waybar/launch.sh
# Notifications
exec-once = mako
# Wallpaper
exec-once = swww query || swww init
exec-once = ~/.config/hypr/scripts/wallpaper.sh init
# Music
exec-once=systemctl --user enable mpd.service && systemctl --user start mpd.service
# Clipboard
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
# Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
# XDG
exec-once = $HOME/.config/hypr/scripts/xdg-portal-hyprland.sh
# Themes
exec-once=gsettings set org.gnome.desktop.interface cursor-theme "Vimix-cursors"
exec-once=gsettings set org.gnome.desktop.interface gtk-theme "Nordic-darker-v40"
exec-once=gsettings set org.gnome.desktop.wm.preferences theme "Nordic-darker-v40"
exec-once = hyprctl setcursor Vimix-cursors 24
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &  
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
