general {
    gaps_in = 10 #5
    gaps_out = 14 #3
    border_size = 3 #2
    col.active_border = $color11
    col.inactive_border = rgba(ffffffff)
    layout = dwindle
}

decoration {
    rounding = 10
    blur {
        enabled = true
        #size = 6
        size = 3
        passes = 2
	      new_optimizations = on
        ignore_opacity=true
        xray=true
    }
    active_opacity=1.0
    inactive_opacity=0.8
    fullscreen_opacity=1.0

    drop_shadow = yes
    shadow_range = 30
    shadow_render_power = 3
    col.shadow = 0x66000000
}
