windowrulev2 = tile,class:^(nvim)$

windowrule=float,title:^(Open File)(.*)$
windowrule=float,title:^(Select a File)(.*)$
windowrule=float,title:^(Choose wallpaper)(.*)$
windowrule=float,title:^(Open Folder)(.*)$
windowrule=float,title:^(Save As)(.*)$
windowrule=float,title:^(Library)(.*)$
windowrulev2=float,opacity 0.8 0.8,title:^(Password Required - Mozilla Firefox)$
windowrulev2 = float,class:^(Lxappearance)$
windowrulev2 = float,class:^(Viewnior)$
windowrulev2 = opacity 0.8 0.8,class:^(kitty)$
windowrulev2 = opacity 0.8 0.8,class:^(rofi)$
windowrulev2 = opacity 0.8 0.8,class:^(thunar)$
windowrulev2 = maximize,title:^(nvim)$
windowrulev2 = float,class:^(org.gnome.Calculator)$
windowrulev2 = size 60% 80%,class:^(org.telegram.desktop|vlc)$
windowrulev2 = center,class:^(Open Files)$
windowrulev2 = opacity 0.8 0.8,title:^(Open Files|ranger)$
windowrulev2 = opacity 1 1,class:^(kitty)$,title:^(nvim)(.*)$
windowrulev2 = noborder,fullscreen:1 # remove border on fullscreen
layerrule = blur,gtk-layer-shell
#windows opened from quicksettings should float
windowrulev2 = float,class:^(blueberry.py)
windowrulev2 = float,class:^(org.twosheds.iwgtk)$
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,title:^(installupdates.sh)$
