# ----------------------------------------------
# DISPLAY
# ----------------------------------------------
monitor=eDP-1,1920x1080@60,1920x0,1
#monitor = eDP-1, addreserved, 40, 0, 0, 0


# ----------------------------------------------
# AUTOSTART
# ----------------------------------------------
source = ~/.config/hypr/conf/autostart.conf


# ----------------------------------------------
# ENVIRONMENT VARIABLES
# ----------------------------------------------
source = ~/.config/hypr/conf/env_var.conf


# ----------------------------------------------
# VARIABLES
# ----------------------------------------------
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
   
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }
    numlock_by_default=true
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
source = ~/.cache/wal/colors-hyprland.conf
source = ~/.config/hypr/conf/decoration.conf


# ----------------------------------------------
# ANIMATIONS
# ----------------------------------------------
source = ~/.config/hypr/conf/animations.conf


# ----------------------------------------------
# LAYOUT
# ----------------------------------------------
dwindle {
    pseudotile = yes
    preserve_split = yes
}
master {
    new_is_master = true
}
gestures {
    workspace_swipe = on
    workspace_swipe_fingers = 3
    workspace_swipe_distance = 500
    workspace_swipe_min_speed_to_force = 100
    workspace_swipe_cancel_ratio = 0.2
}
device:epic-mouse-v1 {
    sensitivity = -0.5
}


# -----------------------------------------------
# WINDOW RULES
# -----------------------------------------------
source = ~/.config/hypr/conf/window_rule.conf


# -----------------------------------------------
# KEYBINDINGS
# -----------------------------------------------
source = ~/.config/hypr/conf/key_bindings.conf


# ---------------------------------------------
# MISC
# ---------------------------------------------
misc {
  disable_hyprland_logo=true
  disable_splash_rendering=true
}
